HistoryAtState/frus

volumes.xconf
Addresses https://github.com/eXistSolutions/hsg-shell/issues/175. Requires eXist PR https://github.com/eXist-db/exist/pull/970.
=> Switch to new range index to speed up rendering.

schema/frus.sch
div/@subtype="referral" and document structure clean up through frus1943
(excluding frus1902app1 and frus1902app2, which need possible restructuring attention)
=> frus-dates-project

volumes/frus1952-54v01p1.xml, volumes/frus1952-54v12p2.xml
to resolve conflicts, used oXygen to compare files. took version with enriched openers as base (due to more changes), and combined with all time-zone enrichment changes in date-related attributes on the document and date levels. these volumes should now contain all enriched aspects and be ready for master branch.
format and indent applied.
@waxcylinderrevival @joewiz
=> 1952-54 series volumes incorporated

volumes/frus1955-57v02.xml, volumes/frus1955-57v03.xml, volumes/frus1955-57v04.xml, volumes/frus1955-57v08.xml, volumes/frus1955-57v09.xml, volumes/frus1955-57v10.xml, volumes/frus1955-57v11.xml, volumes/frus1955-57v23p1.xml, volumes/frus1955-57v23p2.xml, volumes/frus1955-57v24.xml, volumes/frus1955-57v25.xml
opener enrichment complete.
also: all missing index cross-references added, no remaining schema/schematron errors. format and indent applied throughout.
=> 1955 57 opener enrichment

volumes/frus1901China.xml, volumes/frus1902app1.xml, volumes/frus1919Parisv01.xml, volumes/frus1949v07p1.xml, volumes/frus1949v07p2.xml, volumes/frus1952-54v01p1.xml, volumes/frus1952-54v12p2.xml, volumes/frus1955-57v02.xml, volumes/frus1955-57v03.xml, volumes/frus1955-57v04.xml, volumes/frus1955-57v08.xml, volumes/frus1955-57v09.xml, volumes/frus1955-57v10.xml, volumes/frus1955-57v11.xml, volumes/frus1955-57v23p1.xml, volumes/frus1955-57v23p2.xml, volumes/frus1955-57v24.xml, volumes/frus1955-57v25.xml
@joewiz issue complete and closed
=> Fixes for issue 168

volumes/frus1977-80v01.xml, volumes/frus1977-80v09.xml, volumes/frus1977-80v17p1.xml, volumes/frus1977-80v17p2.xml, volumes/frus1977-80v17p3.xml, volumes/frus1977-80v21.xml, volumes/frus1977-80v29.xml, volumes/frus1977-80v30.xml
Opener enrichment task complete throughout FRUS volumes
=> Opener enrichment reagan carter subseries

schema/frus.odd
Hi, Joe, 
Could you please review this pull request, which relates to changes in https://github.com/HistoryAtState/hsg-project/pull/52 ?
Thank you,
Amanda
=> Revise Review Procedures to match updated transformation labels

README.md, bibliography.xconf.tmpl, build.properties.xml, build.xml, code-tables.xconf, code-tables.xconf.tmpl, expath-pkg.xml, expath-pkg.xml.tmpl, volumes.xconf.tmpl
**Build env. specific xars, with and without triggers:**
* default ant task `ant`: create 1 default xar without (replication)
triggers
* ant task `ant xar-dev` will create 2 xar files, one with and one
without triggers, the triggers will contain the dev environment
variables
* ant task `ant xar-prod` will create 2 xar files, one with and one
without triggers, the triggers will contain the prod environment
variables
* extract configuration from `expath-pgk.xml` to `build.properties.xml
* update readme with build documentation
=> Enhance build: Add ant tasks for creating 2 xars in dev and prod and for handling the replication triggers

.gitignore, build.properties.xml, modules/lib/frus-toc.xsl, modules/toc.xqm, modules/triggers.xqm, post-install.xql, repo.xml.tmpl, volumes.xconf
This PR incorporates EB's work from https://github.com/HistoryAtState/frus/pull/309 and thus supersedes that PR. I'll merge this and close their original PR, to avoid the need to rebase the original PR.
=> Accept EB TOC sidebar and facsimile work

.github/dependabot.yml, .github/workflows/build.yml, .releaserc, README.md, commitlint.config.cjs, commitlint.config.js
empty type create patch release
enable linting on ci
=> feat(lint): adjust linter

.github/workflows/build.yml
linter ran without access to sourcecode
=> refactor(ci): change lint phase

bibliography/frus1993-00v29.xml
Updating status of Clinton volume per Kathy's request
=> Update publication-status of volume

frus-toc/frus1969-76v19p2-toc.xml, frus-toc/frus1977-80v22-toc.xml, frus-toc/frus1977-80v23-toc.xml, frus-toc/frus1981-88v05-toc.xml, frus-toc/frus1981-88v06-toc.xml, frus-toc/frus1981-88v41-toc.xml, volumes/frus1969-76v19p2.xml
@joewiz ready for silent upload!
=> Publish reviewed born-digital indexes

frus-toc/frus1981-88v24-toc.xml
@joewiz press release missing from north africa, ready to be added to site
=> fix: north africa press release

repo.xml, schema/frus-dates.sch, tests/frus-dates-sch.xspec
… where it appears to have been appended without basis
=> Flag "+00:00" timezone indicators in dateline attributes

repo.xml
edits to SS–20 index entries from v04 compiler review
=> minor index edits

frus-toc/frus1964-68v23-toc.xml, repo.xml
=> mailbox typo fix

bibliography/frus1989-92v03.xml, bibliography/frus1989-92v04.xml, repo.xml
=> bush title updates

repo.xml
h/t to @machalou for spotting the initial typo
=> Fix footnote refs in frus1981-88v05

repo.xml
@joewiz persname IDs for both Khomeinis corrected
=> Persname fixes 05 2025

.github/workflows/build.yml, .gitignore, .releaserc, conventionalcommits.config.cjs, expath-pkg.xml
This aligns frus with all other data repositories and allows tuttle, ansible and xst to work together.
=> ci: add expath-pkg.xml, commit toc only on master

volumes/frus1870.xml, volumes/frus1934v04.xml, volumes/frus1955-57v23p1.xml, volumes/frus1961-63v06.xml, volumes/frus1961-63v08.xml, volumes/frus1961-63v21.xml, volumes/frus1964-68v17.xml, volumes/frus1964-68v22.xml, volumes/frus1964-68v34.xml, volumes/frus1969-76v01.xml, volumes/frus1969-76v03.xml, volumes/frus1969-76v19p1.xml, volumes/frus1969-76ve05p2.xml, volumes/frus1969-76ve15p1.xml, volumes/frus1977-80v17p1.xml, volumes/frus1977-80v29.xml
@joewiz Typos fixed in frus1895p2 and frus1961-63v21
=> Address oddities with close square brackets

.github/workflows/build.yml, .github/workflows/pr-dispatch.yml, .github/workflows/pr-external.yml, .github/workflows/pr-internal.yml, .last-modified/README.md, README.md
@windauer we will only see the full effect of these changes after they have been merged to `master` due to GitHub security settings. 
please let CI finish though before merging. 
@joewiz note these xmllint warnings
```
./volumes/frus1977-80v22.xml:70430: element item: validity error : ID sub-ff2a5b already defined
<item xml:id="sub-ff2a5b">Mondale, Walter, m
^
./volumes/frus1977-80v22.xml:70587: element item: validity error : ID sub-9d029f already defined
<item xml:id="sub-9d029f">Marcos, Ferdinand,
^
```
=> Fix ci generate
